<?php
require_once 'config.php';

// Very simple PDF generation that ensures text is visible
function generateVisiblePDF($programs, $reportType, $startDate, $endDate) {
    // Create a minimal PDF structure
    $pdf = "%PDF-1.4\n";
    $pdf .= "1 0 obj\n";
    $pdf .= "<<\n";
    $pdf .= "/Type /Catalog\n";
    $pdf .= "/Pages 2 0 R\n";
    $pdf .= ">>\n";
    $pdf .= "endobj\n";
    
    $pdf .= "2 0 obj\n";
    $pdf .= "<<\n";
    $pdf .= "/Type /Pages\n";
    $pdf .= "/Kids [3 0 R]\n";
    $pdf .= "/Count 1\n";
    $pdf .= ">>\n";
    $pdf .= "endobj\n";
    
    // Create the page content with very simple text positioning
    $content = "BT\n";
    
    // Header - Start at top
    $content .= "/F1 16 Tf\n";
    $content .= "50 750 Td\n";
    $content .= "(KEDAH STATE GOVERNMENT) Tj\n";
    $content .= "0 -25 Td\n";
    $content .= "/F1 14 Tf\n";
    $content .= "(PROGRAM MANAGEMENT SYSTEM) Tj\n";
    $content .= "0 -30 Td\n";
    $content .= "/F1 18 Tf\n";
    $content .= "(" . strtoupper($reportType) . " PROGRAMS REPORT) Tj\n";
    $content .= "0 -40 Td\n";
    
    // Report info
    $content .= "/F1 10 Tf\n";
    $content .= "(Generated: " . date('d-m-Y H:i:s') . ") Tj\n";
    $content .= "0 -20 Td\n";
    
    // Summary
    $totalBudget = array_sum(array_column($programs, 'budget'));
    $content .= "/F1 12 Tf\n";
    $content .= "(SUMMARY) Tj\n";
    $content .= "0 -20 Td\n";
    $content .= "/F1 10 Tf\n";
    $content .= "(Total Programs: " . count($programs) . ") Tj\n";
    $content .= "0 -15 Td\n";
    $content .= "(Total Budget: RM " . number_format($totalBudget, 0) . ") Tj\n";
    $content .= "0 -30 Td\n";
    
    // Program details header
    $content .= "/F1 12 Tf\n";
    $content .= "(APPROVED PROGRAMS LIST) Tj\n";
    $content .= "0 -25 Td\n";
    
    // List each program with simple positioning
    foreach ($programs as $index => $program) {
        $content .= "/F1 10 Tf\n";
        $content .= "0 -15 Td\n";
        
        // Create a simple line for each program
        $title = isset($program['title']) ? substr($program['title'], 0, 40) : 'No Title';
        $status = isset($program['status']) ? strtoupper($program['status']) : 'UNKNOWN';
        $budget = isset($program['budget']) ? number_format($program['budget'], 0) : '0';
        $date = isset($program['created_at']) ? date('d/m/Y', strtotime($program['created_at'])) : 'N/A';
        
        $line = ($index + 1) . ". " . $title . " - " . $status . " - RM " . $budget . " - " . $date;
        $content .= "(" . $line . ") Tj\n";
    }
    
    // Footer
    $content .= "0 -30 Td\n";
    $content .= "/F1 10 Tf\n";
    $content .= "(Generated by Kedah State Government Program Management System) Tj\n";
    $content .= "0 -15 Td\n";
    $content .= "(For official use only) Tj\n";
    
    $content .= "ET\n";
    
    $pdf .= "3 0 obj\n";
    $pdf .= "<<\n";
    $pdf .= "/Type /Page\n";
    $pdf .= "/Parent 2 0 R\n";
    $pdf .= "/MediaBox [0 0 612 792]\n";
    $pdf .= "/Contents 4 0 R\n";
    $pdf .= ">>\n";
    $pdf .= "endobj\n";
    
    $pdf .= "4 0 obj\n";
    $pdf .= "<<\n";
    $pdf .= "/Length " . strlen($content) . "\n";
    $pdf .= ">>\n";
    $pdf .= "stream\n";
    $pdf .= $content;
    $pdf .= "endstream\n";
    $pdf .= "endobj\n";
    
    $pdf .= "xref\n";
    $pdf .= "0 5\n";
    $pdf .= "0000000000 65535 f \n";
    $pdf .= "0000000009 00000 n \n";
    $pdf .= "0000000058 00000 n \n";
    $pdf .= "0000000115 00000 n \n";
    $pdf .= "0000000250 00000 n \n";
    $pdf .= "trailer\n";
    $pdf .= "<<\n";
    $pdf .= "/Size 5\n";
    $pdf .= "/Root 1 0 R\n";
    $pdf .= ">>\n";
    $pdf .= "startxref\n";
    $pdf .= (strlen($pdf) - 1) . "\n";
    $pdf .= "%%EOF\n";
    
    return $pdf;
}

// Handle the report generation
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    try {
        $pdo = getConnection();
        
        $input = json_decode(file_get_contents('php://input'), true);
        $reportType = $input['reportType'] ?? 'all';
        $startDate = $input['startDate'] ?? '';
        $endDate = $input['endDate'] ?? '';
        
        // Build the SQL query based on report type
        $whereConditions = [];
        $params = [];
        
        if ($reportType === 'approved') {
            $whereConditions[] = "p.status = 'approved'";
        } elseif ($reportType === 'rejected') {
            $whereConditions[] = "p.status = 'rejected'";
        }
        
        if ($startDate) {
            $whereConditions[] = "p.created_at >= ?";
            $params[] = $startDate . ' 00:00:00';
        }
        
        if ($endDate) {
            $whereConditions[] = "p.created_at <= ?";
            $params[] = $endDate . ' 23:59:59';
        }
        
        $whereClause = '';
        if (!empty($whereConditions)) {
            $whereClause = " WHERE " . implode(" AND ", $whereConditions);
        }
        
        $sql = "
            SELECT p.*, u.name as user_name, u.role as user_role,
                   a.name as approver_name, r.name as rejector_name
            FROM programs p 
            LEFT JOIN users u ON p.user_id = u.id 
            LEFT JOIN users a ON p.approved_by = a.id
            LEFT JOIN users r ON p.rejected_by = r.id
            {$whereClause}
            ORDER BY p.created_at DESC
        ";
        
        $stmt = $pdo->prepare($sql);
        $stmt->execute($params);
        $programs = $stmt->fetchAll(PDO::FETCH_ASSOC);
        
        // Generate visible PDF
        $pdfContent = generateVisiblePDF($programs, $reportType, $startDate, $endDate);
        
        // Set headers for PDF download
        header('Content-Type: application/pdf');
        header('Content-Disposition: attachment; filename="' . $reportType . '_visible_report_' . date('Y-m-d_H-i-s') . '.pdf"');
        header('Content-Length: ' . strlen($pdfContent));
        
        echo $pdfContent;
        
    } catch (Exception $e) {
        error_log("Error generating visible PDF report: " . $e->getMessage());
        http_response_code(500);
        echo json_encode(['error' => 'Failed to generate PDF report']);
    }
} else {
    http_response_code(405);
    echo json_encode(['error' => 'Method not allowed']);
}
?> 